### ISSUE TITLE
Code Organization 

### ISSUE THREAD

**Issue by tchasinga** [khanh-devos/TO-DO-LIST#10]
Good Job so far but you're almost there

kindly I suggest you to add and fix those following requirements

```
export const getData = () => (JSON.parse(localStorage.getItem('tasks')) || [
  {
    index: 1,
    description: 'washing the dishes',
    completed: false,
  },
  {
    index: 2,
    description: 'finish TO DO LIST project',
    completed: false,
  },
  {
    index: 3,
    description: 'implement Drag-Drop feature',
    completed: false,
  },
]);
```
instead of saving data by using Javascript Objects, I suggest you to apply for a local Store of your browser
and the important part of the ES06 you should add directories  **Called Modules to store your all file which is not connected with the main file**

**Comment by khanh-devos** [comment]
Thank you @tchasinga,
"Modules" folder is a good idea, I will follow this immediately.
